# Generated by Django 5.0.2 on 2024-02-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oswapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='var4',
            field=models.CharField(help_text='Введите четвертый вариант ответа', max_length=100, null=True, verbose_name='Четвертый вариант ответа'),
        ),
        migrations.AlterField(
            model_name='question',
            name='var5',
            field=models.CharField(help_text='Введите пятый вариант ответа', max_length=100, null=True, verbose_name='Пятый вариант ответа'),
        ),
        migrations.AlterField(
            model_name='question',
            name='var6',
            field=models.CharField(help_text='Введите шестой вариант ответа', max_length=100, null=True, verbose_name='Шестой вариант ответа'),
        ),
    ]
