# Generated by Django 5.0.2 on 2024-02-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oswapp', '0003_alter_question_var4_alter_question_var5_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer_string', models.CharField(max_length=6)),
                ('id_number_string', models.CharField(max_length=6)),
            ],
        ),
    ]
