# Generated by Django 5.0.2 on 2024-02-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oswapp', '0005_answers_right_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='right_answers',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
