# Generated by Django 5.0.2 on 2024-02-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oswapp', '0006_answers_right_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='RightAnswersCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_answers_count', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='answers',
            name='right_answers',
        ),
    ]
