# Generated by Django 5.0.2 on 2024-02-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oswapp', '0007_rightanswerscount_remove_answers_right_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='rightanswerscount',
            name='id_r_a_c',
            field=models.CharField(default=0, max_length=6),
        ),
    ]
