# Generated by Django 5.0.2 on 2024-02-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oswapp', '0008_rightanswerscount_id_r_a_c'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RightAnswersCount',
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_var_number',
            field=models.CharField(help_text='Введите номер правильного ответа', max_length=6, verbose_name='Номер правильного ответа'),
        ),
        migrations.AlterField(
            model_name='question',
            name='number',
            field=models.CharField(help_text='Введите номер вопроса', max_length=6, verbose_name='Номер вопроса'),
        ),
    ]
