# Generated by Django 5.0.2 on 2024-02-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oswapp', '0009_delete_rightanswerscount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='color_check',
            field=models.CharField(default=False, max_length=1),
        ),
    ]
