# Generated by Django 5.0.2 on 2024-02-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oswapp', '0010_answers_color_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers_color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_check', models.CharField(default=False, max_length=1)),
                ('id_num_answers_color', models.CharField(max_length=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='answers',
            name='color_check',
        ),
    ]
