# Generated by Django 5.0.2 on 2024-03-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oswapp', '0012_alter_question_help_text_alter_question_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='number',
            field=models.IntegerField(help_text='Введите номер вопроса', verbose_name='Номер вопроса'),
        ),
    ]
