# Generated by Django 5.0.2 on 2024-03-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oswapp', '0013_alter_question_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answers_color',
        ),
        migrations.AddField(
            model_name='answers',
            name='color_check',
            field=models.CharField(default=False, max_length=1),
        ),
        migrations.AddField(
            model_name='answers',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='answers',
            name='id_number_string',
            field=models.IntegerField(),
        ),
    ]
