# Generated by Django 5.0.2 on 2024-03-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oswapp', '0016_remove_answers_color_check_remove_answers_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='right_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='color_check',
            field=models.BooleanField(default=False),
        ),
    ]
