# Generated by Django 5.0.2 on 2024-04-24 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oswapp', '0019_question_question_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answers',
        ),
        migrations.RemoveField(
            model_name='question',
            name='color_check',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_count',
        ),
        migrations.RemoveField(
            model_name='question',
            name='right_check',
        ),
    ]
